[project]
name = "digital-city-int-grateur-ia-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Éric Jonet", email = "arimbourg@ariworld.eu" }
]
requires-python = ">=3.12.14"
dependencies = []

[project.scripts]
digital-city-int-grateur-ia-demo = "digital_city_int_grateur_ia_demo:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
